name: Release

on:
  - workflow_dispatch

jobs:
  release:
    name: Build + Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci
        env:
          CI: true

      - name: Build
        run: npx nx run nx-size-limit:build

      - name: Release
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package : ./dist/packages/nx-size-limit/package.json
