name: release

on:
  workflow_dispatch:

jobs:
  release:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci
        env:
          CI: true

      - name: Build
        run: npx nx run nx-size-limit:build

      - name: Release
        run: npx nx run nx-size-limit:release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
